{
    "name": "SaaS: Domain names",
    "images": [],
    "version": "14.0.0.1.0",
    "author": "IT-Projects LLC, Eugene Molotov",
    "support": "it@it-projects.info",
    "license": "AGPL-3",
    "depends": ["saas"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "security/ir.model.access.csv",
        "views/saas_db_views.xml",
        "views/saas_domain_name_views.xml",
        "views/saas_view.xml",
    ],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
