{
    "name": "Tests form remote saas operator",
    "author": "IT-Projects LLC, Eugene Molotov",
    "support": "it@it-projects.info",
    "license": "AGPL-3",
    "version": "14.0.0.1.0",
    "depends": ["saas_operator_remote"],
    "external_dependencies": {"python": [], "bin": []},
    "data": ["data/saas_operator_data.xml"],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
